[pytest]
pythonpath = .
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True

# 基础配置
minversion = 6.0
testpaths = testCase
python_files = test_*.py
python_classes = Test*
python_functions = test_*
log_cli = true
log_cli_level = INFO

addopts = -v -s --strict-markers --alluredir=testReport/allure-results --clean-alluredir
# 其他有用的配置